export const groupSingle = {
  id: 1,
  name: "Group1",
  img: "/default_group_pic.png",
  tags: ["hobbies", "education", "gaming"],
  members: [{ id: 1 }, { id: 2 }, { id: 3 }],
};

export const groupsSmall = [
  {
    id: 1,
    name: "Group1",
    img: "/default_group_pic.png",
    tags: ["education"],
    postFrequency: 0,
    members: [{ id: 1 }, { id: 2 }, { id: 3 }],
  },
  {
    id: 2,
    name: "Group2",
    img: "/default_group_pic.png",
    tags: ["education"],
    postFrequency: 0,
    members: [{ id: 2 }, { id: 4 }, { id: 6 }],
  },
  {
    id: 3,
    name: "Group3",
    img: "/default_group_pic.png",
    tags: ["hobbies", "gaming", "education"],
    postFrequency: 0,
    members: [{ id: 1 }, { id: 3 }, { id: 5 }],
  },
  {
    id: 4,
    name: "Group4",
    img: "/default_group_pic.png",
    tags: ["food", "travel", "miscellaneous"],
    postFrequency: 0,
    members: [{ id: 2 }, { id: 4 }],
  },
  {
    id: 5,
    name: "Group5",
    img: "/default_group_pic.png",
    tags: ["business", "hobbies", "gaming"],
    postFrequency: 0,
    members: [{ id: 1 }, { id: 5 }],
  },
  {
    id: 6,
    name: "Group6",
    img: "/default_group_pic.png",
    tags: ["health", "pets"],
    postFrequency: 0,
    members: [{ id: 3 }, { id: 4 }],
  },
  {
    id: 7,
    name: "Group7",
    img: "/default_group_pic.png",
    tags: ["travel", "food", "business"],
    postFrequency: 0,
    members: [{ id: 2 }, { id: 5 }],
  },
  {
    id: 8,
    name: "Group8",
    img: "/default_group_pic.png",
    tags: ["gaming", "hobbies", "miscellaneous"],
    postFrequency: 0,
    members: [{ id: 1 }, { id: 3 }],
  },
  {
    id: 9,
    name: "Group9",
    img: "/default_group_pic.png",
    tags: ["education", "health", "pets"],
    postFrequency: 0,
    members: [{ id: 4 }, { id: 5 }],
  },
];
